version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_service
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - dev-db:/app/db
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:8000/api
    container_name: frontend_service
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  dev-db: